### ISSUE TITLE
Unable to find packages in requirements.txt

### ISSUE THREAD

**Issue by jacobtyq** [SilverJan/cdc-camper#1]
Running `pip3 install -r requirements.txt` results in an error 

```
ERROR: Could not find a version that satisfies the requirement python3-yaml (from versions: none)
ERROR: No matching distribution found for python3-yaml
```

I cannot seem to find either `python3-yaml` or `python3-selenium` on https://pypi.org/. 
`pip3 search <package-name>` is out of the question as well as it's been disabled.

Are there other ways to get the packages in requirements.txt?

**Comment by SilverJan** [comment]
You're right. `python3-yaml` and `python3-selenium` are the Ubuntu packages. I updated the `requirements.txt` with the correct Python package names.
